app/mystic_music/models.py
from . import db
import datetime

class User(db.Document):
    id = db.StringField(required=True, primary_key=True, null=False)
    display_name = db.StringField(required=True, unique=True, max_length=32, null=False)
    created = db.DateTimeField(required=True, default=datetime.datetime.utcnow, null=False)
    last_login = db.DateTimeField(required=True, default=datetime.datetime.utcnow, null=False)
    songs = db.ListField()

class Groups(db.Document):
    id = db.IntField(required=True, primary_key=True, null=False)
    users = db.ListField()

app/mystic_music/__init__.py
from flask import Flask, current_app
from flask_mongoengine import MongoEngine
from flask_session import Session
from config import config

db = MongoEngine()
sess = Session()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    sess.init_app(app)

    from . account import account as accountBlueprint
    app.register_blueprint(accountBlueprint, url_prefix='/account')

    from . main import main as mainBlueprint
    app.register_blueprint(mainBlueprint)

   

    return app

app/mystic_music/account/__init__.py
from flask import Blueprint

account = Blueprint('account', __name__)

from . import views

app/mystic_music/account/views.py
############
# Packages #
############
from flask import render_template, session, request, redirect, g, current_app, url_for, flash
import spotipy
import uuid
from functools import wraps
import os
import datetime

###########
# Modules #
###########
from . import account
from .. models import User

#############
# Functions #
#############

# Session Cache Path #
def sessionCachePath():
    return current_app.config["SPOTIFY_CACHE_FOLDER"] + session.get("id")


# Login Required 
def loginRequired(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):

        # Check if ID is in session
        if session.get("id") is None:
            return redirect(url_for("account.login"))
        
        # Define Spotify Cache and Auth Handler Variables
        cacheHandler = spotipy.cache_handler.CacheFileHandler(cache_path=sessionCachePath())
        authManager = spotipy.oauth2.SpotifyOAuth(cache_handler=cacheHandler)

        # If Token is not valid or expired then redirect to Login
        if not authManager.validate_token(cacheHandler.get_cached_token()):
            return redirect(url_for("account.login"))

        # Define Spotify Variable 
        spotify = spotipy.Spotify(auth_manager=authManager)

        # Make Spotify variable global
        g.spotify = spotify
        
        return f(*args, **kwargs)
    return decorated_function


# Add Track List to DB #
def addTrackListToDB(spotify, userID):

    # Get user from the DB
    user = User.objects(id=userID).first()

    # Clear existing Songs 
    user.songs = []
    user.save()
    
    # Get number of saved tracks
    numberOfTracks = spotify.current_user_saved_tracks(market="GB")["total"]
    
    # Query the API in increments of 20
    for offset in range(0, numberOfTracks, 20):
        
        # Query the API and assign result to results
        results = spotify.current_user_saved_tracks(market="GB", offset=offset)["items"]

        # Loop through the Results
        for track in results:

            # Add song ID to the DB
            user.songs.append(track["track"]["id"])
            user.save()


#########
# Login #
#########           
@account.route('/login')
def login():

    # Assign visitor a Random ID
    if not session.get("id"):
        session["id"] = str(uuid.uuid4())

    # Define Spotify Cache and Auth Handler Variables
    cacheHandler = spotipy.cache_handler.CacheFileHandler(cache_path=sessionCachePath())
    authManager = spotipy.oauth2.SpotifyOAuth(scope='user-library-read',
                                                cache_handler=cacheHandler, 
                                                show_dialog=True)

    # If user just logged in 
    if request.args.get("code"):
        authManager.get_access_token(request.args.get("code"))
        spotify = spotipy.Spotify(auth_manager=authManager)

        # Get ID and Display Name
        userID = spotify.me()["id"]
        displayName = spotify.me()["display_name"]

        # Check if user in DB
        user = User.objects(id=userID).first()

        # If user is not in DB then add them and sync there Spotify account 
        if user is None:
            User(id=userID, display_name=displayName).save()
            addTrackListToDB(spotify, userID)
        
        # If the user is in the DB then update last login
        else:
            user.last_login = datetime.datetime.utcnow
            user.save()

        # Redirect to the Account Dashboard
        return redirect(url_for("account.dashboard"))

    #  Redirect to Authorization URL as user is not authenticated!
    if not authManager.validate_token(cacheHandler.get_cached_token()):
        authUrl = authManager.get_authorize_url()
        return redirect(authUrl)

    # If the token is not valid or not in URL redirect to the Authorization URL
    authUrl = authManager.get_authorize_url()
    return redirect(authUrl)


###########
# Log Out #
###########
@account.route('/log-out')
def logOut():
    
    try:
        # Remove the CACHE file (.cache-test) so that a new user can authorize.
        os.remove(sessionCachePath())
        session.clear()
    except OSError as e:
        print ("Error: %s - %s." % (e.filename, e.strerror))
    flash('You have been logged out!', 'success')
    return redirect(url_for("main.index"))


#############
# Dashboard #
#############
@account.route('/dashboard')
@loginRequired
def dashboard():

    # Spotify Variables 
    spotify = g.spotify
    displayName = spotify.me()["display_name"]

    # Return Dashboard Template with the variable displayName 
    return render_template("account/dashboard.html", displayName=displayName)


########
# Sync #
########
@account.route('/sync')
@loginRequired
def sync():

    # Spotify Variables 
    spotify = g.spotify
    userID = spotify.me()["id"]

    # Call the function for adding the track list to the DB
    addTrackListToDB((spotify, userID)

    # Flash success message and redirect to the account dashboard
    flash('You\'re Spotify account has been synced with Mystic Music!', 'success')
    return redirect(url_for("account.dashboard"))


##########
# Delete #
##########
@account.route('/delete')
@loginRequired
def delete(): 

    # Spotify Variables 
    spotify = g.spotify
    userID = spotify.me()["id"]

    # Get user from the DB and delete
    user = User.objects(id=userID).first()
    user.delete()

    # Flash success message and redirect to the homepage
    flash('You\'re Mystic Music account has been deleted!', 'success')
    return redirect(url_for("main.index"))

app/mystic_music/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/mystic_music/main/views.py
from flask import render_template, session
from . import main

#########
# Index #
#########
@main.route('/')
def index():
    return render_template('index.html')


###########
# Contact #
###########
@main.route('/contact')
def contact():
    return render_template('contact.html')


########
# Get Started #
########
@main.route('/get-started')
def getStarted():
    return render_template('get-started.html')


#########
# About #
#########
@main.route('/about')
def about():
    return render_template('about.html')

app/mystic_music/templates/get-started.html
{% extends "layout.html" %}

{% block title %} Get Started {% endblock %}

{% block content %}
<div class="center-container">
    <h1> Get Started </h1>
    <p> Please click the sign in button to allow Mystic Music to access your Spotify account.</p>
     
    <a href="{{ url_for('account.login') }}"> <button>  Login with Spotify </button> </a>
     
    <p> By clicking the sign in button you agree to our privacy policy. </p>
</div>

{% endblock %}

app/mystic_music/templates/index.html
{% extends "layout.html" %}



{% block title %} Home {% endblock %}

{% block content %}
<div class="center-container">
    <h1> Welcome to Mystic Music </h1>
    <h2> Mystic Music is a Spotify App to gather your friends music</h2>
    <p> To get started click or tap Get Started. </p>
   
    <a class="button" href="{{ url_for('main.getStarted') }}"> Get Started</a>  
</div>

{% endblock %}

app/mystic_music/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Mystic Music - {% block title %}{% endblock %} </title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/picnic.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/layout.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/simpleNotification.css') }}">
    {% block head %} {% endblock %}
</head>
<body>

    <!-- Nav and Content Container -->
    <div class="container">
           
        <!-- Navigation Bar -->
        <nav>

            <!-- Logo -->
            <a class="brand" href="">
                <img class="logo" src="{{ url_for('static', filename='img/logo-c.png') }}" width="100px;" >
            </a> 
        
            <!-- Center Nav -->
            <div class="menu-center menu">
               <h1> Mystic Music </h1>
            </div>
            
            <!-- Right Nav -->
            <div class="menu-right menu">
                
            </div>

        </nav>

        <!-- Content -->
        <main>

            {% block content %}
                
            {% endblock %}
    
        </main>

    </div>

    <!-- Footer -->
    <footer class="footer">
        Released under <a href="https://github.com/bxdavies/lmrun/blob/main/LICENSE"> GNU General Public License v3.0 </a> on <a href="https://github.com/bxdavies/lmrun/">GitHub</a>
        <br>
        Developed by <a href="https://bxdavies.co.uk"> @bxdavies</a> 
    </footer>


   
    <script src="{{ url_for('static', filename='js/simpleNotification.js') }}"></script>
    <script src="{{ url_for('static', filename='js/notification.js') }}"></script>
    {% for category, message in get_flashed_messages(with_categories=True) %}
    <script>
        category = '{{ category }}';
        message = '{{ message }}';
        console.log(category, message)
        notification(category, message);
    </script>
    {% endfor %}

</body>
</html>